/**
 * Created by Andrew on 9/22/2015.
 */
import javax.swing.*;
import java.awt.*;

public class OG {

    JFrame frame;

    public static void main(String[] args) {

//        OG GenePalette
//        new OG(args[0]);
//        OG Independent
        new OG("");
//        new OG("AGTGCCAGCCTGGCGCCCGCGACTGCCTGCCCCAGCCCCTCAGTGGCGGCTTGCTCTCTTCTCTCGCTCCGAACCAGACACAGCCGCTGCCGCTGCCGTCCGGCGCGCTACAGACTCCCGAGAACAGCCCTGGCTGTCAGCGAGCACCAGCCGCTTCCTGTCCCCATCGCGGAGACTGGAGGGGCGCACCACGGCCATGGAGCCAGAGGCGCTTCAGGAGGCAAGAGAAGTCCCCGCGCGCTCCGCAGCCCGGCGCAGCTCATGGTGAGCGCCCTCTGGGGCTCGAGGGTCCCTTGGCTGAGGGGGCGCATCCTCGGGGTGCCCGATGGGGCTGCCTGGGGGTCGCAGGGCTGAAGTTGGGACCGCGCACAGACCGCCCCTGCAGTCCAGCCCGAAATGCTGCCGCCAGGCAGCAACGGCACCGCGTACCCGGGGCAGTTCGCTCTATACCAGCAGCTGGCGCAGGGGAACGCCGTGGGGGGCTCGGCGGGGGCACCGCCACTGGGGCCCTCACAGGTGGTCACCGCCTGCCTGCTGACCCTACTCATCATCTGGACCCTGCTGGGCAACGTGCTGGTGTGCGCAGCCATCGTGCGGAGCCGCCACCTGCGCGCCAACATGACCAACGTCTTCATCGTGTCTCTGGCCGTGTCAGACCTTTTCGTGGCGCTGCTGGTCATGCCCTGGAAGGCAGTCGCCGAGGTGGCCGGTTACTGGCCCTTTGGAGCGTTCTGCGACGTCTGGGTGGCCTTCGACATCATGTGCTCCACTGCCTCCATCCTGAACCTGTGCGTCATCAGCGTGGACCGCTACTGGGCCATCTCCAGGCCCTTCCGCTACAAGCGCAAGATGACTCAGCGCATGGCCTTGGTCATGGTCGGCCTGGCATGGACCTTGTCCATCCTCATCTCCTTCATTCCGGTCCAGCTCAACTGGCACAGGGACCAGGCGGCCTCTTGGGGCGGGCTGGACCTGCCAAACAACCTGGCCAACTGGACGCCCTGGGAGGAGGACTTTTGGGAGCCCGACGTGAATGCAGAGAACTGTGACTCCAGCCTGAATCGAACCTACGCCATCTCTTCCTCGCTCATCAGCTTCTACATCCCCGTTGCCATCATGATCGTGACCTACACGCGCATCTACCGCATCGCCCAGGTGCAGATCCGCAGGATTTCCTCCCTGGAGAGGGCCGCAGAGCACGCGCAGAGCTGCCGGAGCAGCGCAGCCTGCGCGCCCGACACCAGCCTGCGCGCTTCCATCAAGAAGGAGACCAAGGTTCTCAAGACCCTGTCGGTGATCATGGGGGTCTTCGTGTGTTGCTGGCTGCCCTTCTTCATCCTTAACTGCATGGTCCCTTTCTGCAGTGGACACCCCGAAGGCCCTCCGGCCGGCTTCCCCTGCGTCAGTGAGACCACCTTCGACGTCTTCGTCTGGTTCGGCTGGGCTAACTCCTCACTCAACCCCGTCATCTATGCCTTCAACGCCGACTTTCAGAAGGTGTTTGCCCAGCTGCTGGGGTGCAGCCACTTCTGCTCCCGCACGCCGGTGGAGACGGTGAACATCAGCAATGAGCTCATCTCCTACAACCAAGACATCGTCTTCCACAAGGAAATCGCAGCTGCCTACATCCACATGATGCCCAACGCCGTTACCCCCGGCAACCGGGAGGTGGACAACGACGAGGAGGAGGGTCCTTTCGATCGCATGTTCCAGATCTATCAGACGTCCCCAGATGGTGACCCTGTTGCTGAGTCTGTCTGGGAGCTGGACTGCGAGGGGGAGATTTCTTTAGACAAAATAACACCTTTCACCCCGAATGGATTCCATTAAACTGCATTAAGAAACCCCCTCATGGATCTGCATAACCGCACAGACATTGACAAGCACGCACACACACGCAAATACATGCCTTTCCAGTGCTGCTCCCTTTATCATGTGTTTCTGTGTAGTAGCTCGTGTGCTTAGAAACCTCACCCCATTGATTGGTAGTTCGAAGAATTGGCAGAAGCAGTTGCAATAAACTCAGTCAAATGTACCCAGCCTACCAGAGATGGACCAACGATCCTATGAGAGAAGAGAGTATGGTGCTGGGTCCTTAAAAAAAAAAATGATACTTGGTCCTTAAAAAATATGCTCTCCCCTCCCTTTTTAAACAAATGGCTTGTTCAGTCACTTGTTTGTGTTTGAATTGATTTTTAAACAGCAGGTTGTGTGTGTGTGCAGTGATGTGGTGGGAGCACAGCTTTCCTGGGTCTGGATTCCCGTGGCTTTGTGCTTATGTCATTTCTTCTCTCTGTGCTGGTGGGGGCCTCTTTACCATAGCTTAAGAAGTATCCCTGATTTATTCTGGTGTCTAATAAACACAGATTATTTGTAAAAAAAAAAAAAAAAAAAAAAA");
    }

    public OG(final String seq) {

        System.setProperty("jsse.enableSNIExtension", "false");

        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                frame = new JFrame();
                frame.setTitle("OG Ortholog Grabber");
                frame.add(new MainPane(seq, frame).getMainPane());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}